import { FlowChart } from './flow-chart';
import { Separator } from '@/components/ui/separator';

export async function generateMetadata({ searchParams }: { searchParams: {[key: string]: string | undefined } }) {
    const title = searchParams['paperId'] ? `${searchParams['paperId']} details` : 'Reports';
    const description = 'Reports generated by Scholar Maps';
    return { title, description };
}

export default function Reports() {
    return (
        <section className="bg-background absolute top-10 lg:left-[16.666%] flex flex-col gap-2 w-full overflow-x-hidden lg:w-5/6">
            <div className="w-full flex flex-col gap-2">
                <div className="h-4" />
                <FlowChart variant="figma" />
            </div>
        </section>
    )
}