import { FlowChart } from './flow-chart';

export async function generateMetadata({ searchParams }: { searchParams: {[key: string]: string | undefined } }) {
    const title = searchParams['paperId'] ? `${searchParams['paperId']} details` : 'Reports';
    const description = 'Reports generated by Scholar Maps';
    return { title, description };
}

export default function Reports() {
    return (
        <section className="bg-background p-4 absolute top-16 lg:left-[16.666%] lg:p-8 flex flex-col gap-2 w-full overflow-x-hidden lg:w-5/6">
            <h1 className="mt-2 lg:mt-0 text-xl lg:text-2xl font-semibold lg:font-bold">Reports</h1>
            <div className="w-full flex flex-col gap-2">
                <div className="h-8" />
                <FlowChart variant="figma" />
            </div>
        </section>
    )
}